language: node_js
node_js:
  - '10'
  - '8'
  - '6'
os:
  - linux
  - windows
sudo: true
install:
  # npm install
  - npm install
before_script:
  # npm install typescript
  - npm install -g typescript
script:
  # Run test script
  - tsc